Develop
AntonBergman103/Lemonade-Stand pull request #1
Opened 2024-05-10 08:17 UTC by AntonBergman103

test

2024-05-13 12:38 UTC, manscronholm requested changes
Granskad! Bra jobbat, men lite grejer att gå igenom 👍

2024-05-13 12:38 UTC, manscronholm-iosoft commented on Lemonade Stand/Components/Pages/Home.razor
> +    <div class="form-group">
Vi bör nog lägga till en presentation av recepten enligt uppgiftsbeskrivningen

2024-05-13 12:38 UTC, manscronholm-iosoft commented on Lemonade Stand/Components/Pages/Home.razor
> +    public NullValidation nullValidation { get; set; }
Behöver du ha denna i och med att du injectar servicen högst upp i komponenten?

2024-05-13 12:38 UTC, manscronholm-iosoft commented on Lemonade Stand/Components/Pages/Home.razor
> +    List<Type> availableFruits = new List<Type> { typeof(Apple), typeof(Orange), typeof(Melon) };
Blir det inte enklare för dig att skapa upp en lista med IFruit där du sen instansierar varje frukt? Då slipper du hålla på med type conversion och sånt där.

2024-05-13 12:38 UTC, manscronholm-iosoft commented on Lemonade Stand/Components/Pages/Home.razor
> +        Console.WriteLine($"Recipes loaded: {recipes.Count}");
```suggestion

```

2024-05-13 12:38 UTC, manscronholm-iosoft commented on Lemonade Stand/Components/Pages/Home.razor
> +        if (errors.Any())
Skulle du kunna flytta in all validering i validation servicen?

2024-05-13 12:38 UTC, manscronholm-iosoft commented on LemonadeStand.Domain/Fruit.cs
> +        public decimal Quantity { get; set; }
Bör quantity vara en del av en frukt? Eller är det snarare en property som hör hemma i ordermodel?

2024-05-13 12:38 UTC, manscronholm-iosoft commented on LemonadeStand.Domain/Fruit.cs
> +    public class Fruit : IFruit // skapar en ny typ av objekt, vi kan skapa många frukter med olika namn
Vilket syfte har denna implementationen? Skulle inte alla olika frukter kunna implementera IFruit direkt?

2024-05-13 12:38 UTC, manscronholm-iosoft commented on LemonadeStand.Domain/IFruit.cs
> +        decimal Quantity { get; set; }
Quantity skall enligt uppgiftsbeskrivningen inte vara en property i IFruit

2024-05-13 12:38 UTC, manscronholm-iosoft commented on LemonadeStand.Domain/IFruit.cs
> +    //en mall för andra koddelar som beskriver en frukt
Behövs denna kommentaren?

2024-05-13 12:38 UTC, manscronholm-iosoft commented on LemonadeStand.Domain/IFruit.cs
> +    public interface IFruit // interface  (ritning/kontrakt/mall)
Behövs denna kommentaren?

2024-05-13 12:38 UTC, manscronholm-iosoft commented on LemonadeStand.Domain/Fruit.cs
> +        public Fruit(string name) // konstruktor
Behövs denna kommentaren?

2024-05-13 12:38 UTC, manscronholm-iosoft commented on LemonadeStand.Application/OrderModel.cs
> +        public string FruitTypeName { get; set; }  // Stores the fruit type name for conversion to Type
Behövs denna kommentaren?

2024-05-13 12:38 UTC, manscronholm-iosoft commented on LemonadeStand.Application/IFruitPressService.cs
> +
Behövs denna kommentaren?

2024-05-13 12:38 UTC, manscronholm-iosoft commented on LemonadeStand.Application/IFruitPressService.cs
> +    }
Behövs denna kommentaren?

2024-05-13 12:38 UTC, manscronholm-iosoft commented on LemonadeStand.Domain/IRecipe.cs
> +    public interface IRecipe // interface  (ritning/kontrakt/mall)
Behövs denna kommentaren?

2024-05-13 12:38 UTC, manscronholm-iosoft commented on LemonadeStand.Application/FruitPressService.cs
> +            List<string> errorMessages = new List<string>(); //istället för att kolla en och en samla alla errors i en lista
Behövs denna kommentaren?

2024-05-13 12:38 UTC, manscronholm-iosoft commented on LemonadeStand.Application/FruitPressService.cs
> +            // check the total quantity of the fruit
Behövs denna kommentaren?

2024-05-13 12:38 UTC, manscronholm-iosoft commented on LemonadeStand.Application/FruitPressService.cs
> +            // If there are any errors, return them all
Behövs denna kommentaren?

2024-05-13 12:38 UTC, manscronholm-iosoft commented on LemonadeStand.Domain/Recipe.cs
> +    {
Behövs denna kommentaren?

2024-05-13 12:38 UTC, manscronholm-iosoft commented on LemonadeStand.Domain/Recipe.cs
> +        //konstruktor
Behövs denna kommentaren?

2024-05-13 12:38 UTC, manscronholm-iosoft commented on LemonadeStand.Application/FruitPressResult.cs
> +        public FruitPressResult(bool succeeded, string message, decimal changeback, decimal excessfruit)
Hur tänker du avseende valet av att använda en konstruktor istället för att initisera objektet med hjälp av setters?

Om du väljer att gå med konstruktor, behöver du ha setters på ovan properties då?

2024-05-13 12:38 UTC, manscronholm-iosoft commented on LemonadeStand.Application/FruitPressService.cs
> +    public class FruitPressService : IFruitPressService
Finns det delar av den här servicen som skulle kunna brytas ut i private metoder, eller till och med en egen klass? Tänk på single-responsibility principen.

2024-05-13 12:38 UTC, manscronholm-iosoft commented on LemonadeStand.Application/IRecipeService.cs
> +        void LoadDefaultRecipes();
Används LoadDefaultRecipes publikt?

2024-05-13 12:38 UTC, manscronholm commented on LemonadeStand.Application/RecipeService.cs
> +        private List<Recipe> recipes = new List<Recipe>();
Skulle man inte kunna lägga till recepten direkt här i instansieringen? Då slipper du Load metoden.

2024-05-13 12:38 UTC, manscronholm commented on LemonadeStand.Domain/Order.cs
> +        public Order(IRecipe recipe, int quantity, int paidAmount)
Samma sak här som ovan konstruktorer. Vilka fördelar ser du med att köra en konstruktor istället för att initialisera objektet med setters? Och om du ändå kör med konstruktor, behöver du har setters då?

2024-05-13 12:38 UTC, manscronholm commented on LemonadeStand.Domain/Recipe.cs
> +        public Recipe(string name, Type fruitType, int pricePerGlass, decimal consumptionPerGlass )
Samma frågeställning här som ovan konstruktorer.

2024-05-13 12:38 UTC, manscronholm commented on LemonadeStand.Application.Test/FruitPressServiceTests.cs
> +        public void InsufficentFundsTest()
Följ gärna standard namngivning för test: What_When_Will
T.ex: Produce_WithInsufficientFunds_WillReturnCorrectErrorMessage.

Då får man en snabb förklaring av testet bara genom att läsa namnet.

https://learn.microsoft.com/en-us/dotnet/core/testing/unit-testing-best-practices#best-practices

2024-05-13 12:38 UTC, manscronholm commented on LemonadeStand.Application.Test/FruitPressServiceTests.cs
> +            int moneyPaid = 9; //not enough
Behövs denna kommentaren?

2024-05-13 12:38 UTC, manscronholm commented on LemonadeStand.Application.Test/FruitPressServiceTests.cs
> +            Assert.Contains("Wrong fruit for that recipe. ", result.Message);
Behövs denna kommentaren?

2024-05-13 12:38 UTC, manscronholm commented on LemonadeStand.Application.Test/FruitPressServiceTests.cs
> +            List<IFruit> fruits = new List<IFruit> { new Orange { Quantity = 1 } }; // wrong fruit & insufficent ammount
Behövs denna kommentaren?

2024-05-13 12:38 UTC, manscronholm commented on LemonadeStand.Application.Test/FruitPressServiceTests.cs
> +            Assert.Contains("Not enough fruit for the beverage. 1 glasses require 2,5 units of fruit. ", result.Message); // Check for insufficient quantity message
Behövs dessa kommentarer?

2024-05-13 12:38 UTC, manscronholm commented on LemonadeStand.Application.Test/FruitPressServiceTests.cs
> +            List<IFruit> fruits = new List<IFruit> { new Apple { Quantity = 5 } };  // expected 2.5 leftover
Behövs denna kommentaren?

2024-05-13 12:38 UTC, manscronholm commented on LemonadeStand.Application.Test/FruitPressServiceTests.cs
> +            int moneyPaid = 20; // expected 10 in change
Behövs denna kommentaren?

2024-05-13 12:38 UTC, manscronholm commented on LemonadeStand.Application.Test/FruitPressServiceTests.cs
> +            List<Recipe> fakeRecipe = new List<Recipe>();
Används denna?

2024-05-13 12:38 UTC, manscronholm commented on LemonadeStand.Application.Test/FruitPressServiceTests.cs
> +            List<Recipe> fakeRecipe = new List<Recipe>();
Används denna?

2024-05-13 12:38 UTC, manscronholm commented on LemonadeStand.Application.Test/FruitPressServiceTests.cs
> +        }
När man behöver många asserts är det ofta ett tecken på att en metod gör för mycket olika saker. 

Hur hade det blivit om du bröt ut kalkyleringslogiken till en separat calculator service t.ex? Hade det kunnat bli renare då?

Jag önskar också att du med en theory hade fler testfall med olika input för att se till att uträkningarna blir korrekta.

2024-05-13 12:38 UTC, manscronholm commented on LemonadeStand.Application.Test/NullValidationTest.cs
> +    public class NullValidationTest
Snygg testklass! Såhär lätta och fina blir dom när dom inte hanterar så mycket olika grejer :)

2024-05-13 12:38 UTC, manscronholm commented on LemonadeStand.Application.Test/NullValidationTest.cs
> +}
Skulle önska ett testfall till. Vad händer om ingenting är fel?

2024-05-13 12:38 UTC, manscronholm commented on LemonadeStand.Application/FruitPressService.cs
> +            decimal excessFruit = fruitCount - totalFruitNeeded;
Kan vi separera ut denna logik till en egen klass för att främja single-responsability principen samt för att öka testbarheten?

Finns det fler delar i denna metod som du skulle kunna tänka dig att bryta ut?

2024-05-13 12:38 UTC, manscronholm-iosoft commented on LemonadeStand.Application/NullValidation.cs
> +    public class NullValidation
Fundera över namngivningen. Förklarar namnet vad som valideras? Är det bara null som valideras?

2024-05-13 12:38 UTC, manscronholm-iosoft commented on LemonadeStand.Test/NullValidationTest.cs
> +    public class NullValidationTest
Dessa filer ligger kvar från ditt gamla testprojekt, ta bort dom. :)

2024-05-13 12:38 UTC, manscronholm-iosoft commented on LemonadeStand.Test/FruitPressServiceTests.cs
> +    public class FruitPressServiceTests
Dessa filer ligger kvar från ditt gamla testprojekt, ta bort dom. :)

2024-05-15 06:03 UTC, AntonBergman103 commented on LemonadeStand.Application/FruitPressService.cs
> +            decimal excessFruit = fruitCount - totalFruitNeeded;
denna tar gärna en lite mer diskussion,gärna hur man ska tänka osv

2024-05-15 06:05 UTC, AntonBergman103 commented on LemonadeStand.Application/FruitPressService.cs
> +    public class FruitPressService : IFruitPressService
diskuterar denna gärna med, hur man ska tänka osv

2024-05-15 06:05 UTC, AntonBergman103 commented on LemonadeStand.Application.Test/FruitPressServiceTests.cs
> +        }
diskuterar denna med

2024-05-15 06:54 UTC, manscronholm requested changes

2024-05-15 06:54 UTC, manscronholm commented on Lemonade Stand/Components/Pages/Home.razor
> +    <div class="form-group">
Kan vi loopa igenom våra recept istället för att hårdkoda värdena? Vad händer om priset på ett recept skulle förändras t.ex? Eller om vi vill lägga till ett nytt recept?

2024-05-15 06:54 UTC, manscronholm commented on Lemonade Stand/Components/Pages/Home.razor
> +            </InputSelect>
Varför använder vi oss inte av en heltals input istället för en select? Bör det vara begränsat till 10?

2024-05-15 06:54 UTC, manscronholm commented on LemonadeStand.Application/OrderValidation.cs
> +        public List<string> ValidateOrder(OrderModel orderModel, IRecipe recipe, ICollection<IFruit> fruits, decimal moneyPaid, int quantityGlass)
Används orderModel?

2024-05-15 06:54 UTC, manscronholm commented on LemonadeStand.Application/RecipeService.cs
> +        private List<Recipe> recipes = new List<Recipe>
en private variable skall alltid namnges med "_" som prefix. I detta fallet alltså: _recipes.

https://learn.microsoft.com/en-us/dotnet/csharp/fundamentals/coding-style/identifier-names#naming-rules

2024-05-15 06:54 UTC, manscronholm commented on LemonadeStand.Application/FruitPressService.cs
> +            _orderValidator = new OrderValidator();
Kan vi använda dependency injection istället för att newa upp validatorn?

2024-05-15 06:54 UTC, manscronholm commented on LemonadeStand.Application/OrderValidation.cs
> +        public List<string> ValidateOrder(OrderModel orderModel, IRecipe recipe, ICollection<IFruit> fruits, decimal moneyPaid, int quantityGlass)
Skulle vi kunna bryta ut delar av denna metoden till mindre private metoder för att öka läsbarheten i koden?

2024-05-15 06:54 UTC, manscronholm commented on LemonadeStand.Application.Test/FruitPressServiceTests.cs
>      public class FruitPressServiceTests
Snyggt! Mycket bättre läsbarheten i den här klassen nu! :)

2024-05-15 06:54 UTC, manscronholm commented on LemonadeStand.Application.Test/FruitPressServiceTests.cs
> +        }
Yes, vi tar en diskussion om detta 👍

2024-05-15 06:54 UTC, manscronholm commented on LemonadeStand.Application/FruitPressService.cs
> +    public class FruitPressService : IFruitPressService
Yes, vi tar en diskussion om detta 👍

2024-05-15 09:05 UTC, manscronholm commented on LemonadeStand.Application/OrderValidation.cs
> +        public List<string> ValidateOrder(OrderModel orderModel, IRecipe recipe, ICollection<IFruit> fruits, decimal moneyPaid, int quantityGlass)
Används orderModel?
Används  fruitCount?

2024-05-15 09:07 UTC, AntonBergman103 commented on LemonadeStand.Application/OrderValidation.cs
> +        public List<string> ValidateOrder(OrderModel orderModel, IRecipe recipe, ICollection<IFruit> fruits, decimal moneyPaid, int quantityGlass)
dom används i sin tur i FruitPressService

2024-05-15 09:10 UTC, manscronholm commented on LemonadeStand.Application/OrderValidation.cs
> +        public List<string> ValidateOrder(OrderModel orderModel, IRecipe recipe, ICollection<IFruit> fruits, decimal moneyPaid, int quantityGlass)
Du gör ingenting med orderModel eller fruitCount i denna klassen.

2024-05-15 09:12 UTC, manscronholm commented on LemonadeStand.Application/OrderValidation.cs
> +        public List<string> ValidateOrder(OrderModel orderModel, IRecipe recipe, ICollection<IFruit> fruits, decimal moneyPaid, int quantityGlass)
CheckIfCorrectFruitAndAmmount() Validerar ingenting just nu. Den returnerar en lista som aldrig används. Kanske något du bör se över

2024-05-15 09:28 UTC, AntonBergman103 commented on LemonadeStand.Application/OrderValidation.cs
> +        public List<string> ValidateOrder(OrderModel orderModel, IRecipe recipe, ICollection<IFruit> fruits, decimal moneyPaid, int quantityGlass)
såg att jag definerade fruitcount två gånger och använder inte resultatet av fruitcount i validateorder som du sa.

2024-05-15 09:32 UTC, manscronholm requested changes

2024-05-15 09:32 UTC, manscronholm commented on LemonadeStand.Application.Test/FruitPressServiceTests.cs
> +        public void ProduceOrder_WithValidInputs_CompleteWithRightMessageBack()
Om jag kör det här testet med en "Invalid input" där jag byter typen av frukt i orderModel till typeof(Orange) så är ändå testet grönt. Bör det bli så?

2024-05-15 09:32 UTC, manscronholm commented on LemonadeStand.Application.Test/FruitPressServiceTests.cs
> +        public void ProduceOrder_WithValidInputs_CompleteWithRightMessageBack()
Kan vara värt att göra ett omvänt testfall för detta.

2024-05-15 09:32 UTC, manscronholm commented on LemonadeStand.Application.Test/FruitPressServiceTests.cs
> +        public void ProduceOrder_WithValidInputs_CompleteWithRightMessageBack()
Nvm. När jag ändrar typen i fruits listan så smäller det, vilket är korrekt.

2024-05-15 09:32 UTC, manscronholm-iosoft commented on LemonadeStand.Application/FruitPressService.cs
> +            }
En snygg lösning där du kan blir av med hela den här loopen är att ersätta den med hjälp av LINQ. Det kan ersättas med:
 
 `var fruitCount = fruits.Count(fruit => fruit.GetType() == recipe.AllowedFruit);`

2024-05-15 09:42 UTC, manscronholm requested changes

2024-05-15 09:42 UTC, manscronholm commented on LemonadeStand.Domain/Order.cs
> +    public class Order
Den här klassen används inte och kan tas bort.

2024-05-15 09:42 UTC, manscronholm commented on LemonadeStand.Application/FruitPressResult.cs
> +namespace LemonadeStand.Domain
Detta namespace stämmer inte.

2024-05-15 09:42 UTC, manscronholm commented on LemonadeStand.Application/IFruitPressService.cs
> +namespace LemonadeStand.Domain
Detta namespace stämmer inte

2024-05-15 09:42 UTC, manscronholm commented on LemonadeStand.Application/IRecipeService.cs
> +namespace LemonadeStand.Application.Interfaces
Detta namespace stämmer inte

2024-05-15 13:29 UTC, manscronholm requested changes

2024-05-15 13:29 UTC, manscronholm commented on LemonadeStand.Application/OrderValidation.cs
>          private static decimal InsufficentAmountOfFruits(IRecipe recipe, ICollection<IFruit> fruits, int quantityGlass, List<string> errorMessages)
Denna metoden returnerar en decimal som aldrig används. Kan med fördel göras om till en void

2024-05-15 14:01 UTC, manscronholm commented
Grymt! Bra jobbat :)

2024-05-15 14:02 UTC, manscronholm approved these changes

2024-05-15 14:02 UTC, merged